config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'projects#index'

  resources :projects, except: :show do
    resources :tasks do
      post :toggle, on: :member
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :tasks, -> { order :position }, dependent: :destroy, inverse_of: :project
  belongs_to :user
  validates :title, presence: true

  accepts_nested_attributes_for :tasks
  default_scope { order 'created_at ASC' }
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  include RailsSortable::Model
  set_sortable :position

  belongs_to :project
  validates :title, presence: true

  scope :by_position, -> { order(:position) }
  scope :completed, -> { where(completed: true) }
  scope :uncompleted, -> { where(completed: false) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :projects, -> { order 'created_at ASC' }, dependent: :destroy, inverse_of: :user
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[edit update destroy]

  def index
    @projects = current_user.projects
    @task = Task.new
  end

  def new
    @project = current_user.projects.new
  end

  def edit; end

  def create
    @project = current_user.projects.new(project_params)
    @task = Task.new
    respond_to do |format|
      if @project.save
        format.js
      else
        format.js { render 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.js
      else
        format.js { render 'edit' }
      end
    end
  end

  def destroy
    @project.destroy
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :deadline)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, except: %i[index new create]
  before_action :set_project, except: %i[index destroy]

  def index
    @tasks = Task.order(:position).all
  end

  def toggle
    @task.toggle(:completed).save
  end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = @project.tasks.new(task_params)
    respond_to do |format|
      if @task.save
        format.js
      else
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.js
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to :js
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:title, :task_deadline)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
  def project_deadline(project)
    project.deadline ? project.deadline.strftime('Deadline is: %B %d, %Y') : 'Set deadline'
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def task_deadline(task)
    task.task_deadline ? task.task_deadline.strftime('Deadline is: %B %d, %Y') : 'Set deadline'
  end
end

app/views/layouts/_navbar.html.erb
<nav class="shadow navbar navbar-position navbar-light blue-gradient rounded-bottom mb-5">
  <span class="navbar-text text-white font-weight-bold text-dark-shadow">Simple TODO LISTS for Rubygarage by Valter0ff</span>
  <% if user_signed_in? %>
		<span class="navbar-text text-white font-weight-bold text-dark-shadow">Account: <%= current_user.email %></span>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="fa fa-user-circle-o text-white font-weight-bold text-dark-shadow"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
    <div class="navbar-nav-row justify-content-end">
			<% if user_signed_in? %>
				<%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link text-white font-weight-bold text-dark-shadow" %>
			<% else %>
				<%= link_to "Login", new_user_session_path, class: "nav-link text-white font-weight-bold text-dark-shadow" %>
				<%= link_to "Create account", new_user_registration_path, class: "nav-link text-white font-weight-bold text-dark-shadow" %>
			<% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubygarage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=1, user-scalable=yes, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="modal-header blue-gradient">
  <h5 class="modal-title text-white font-weight-bold text-dark-shadow" id="exampleModalLabel">Enter here project title</h5>
  <button type="button" class="close text-dark-shadow fa-heading-style" data-dismiss="modal" aria-label="Close" aria-hidden="true">×</button>
 </div>
<div class="modal-body light-grey">
  <%= form_with(model: project) do |form| %>
    <% if project.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
       <%= form.text_field :title, required: true,
        class:"form-control border-left-0 border-bottom-0 border-secondary" %>
    </div>
    <div class="d-flex actions justify-content-center">
      <%= form.submit class:"btn mt-3 px-3 text-white font-weight-bold border-top  border-secondary green-gradient text-dark-shadow" %>
    </div>
   <% end %>
</div>

app/views/projects/_project.html.erb
<ul class="shadow list-group mb-5 border-bottom border-secondary rounded-bottom" id="<%=dom_id(project)%>">
  <li class="list-group-item p-0 blue-gradient">
    <div class="row mx-0">
      <div class="col-auto m-1 px-2 pt-2 flatpickr">
        <%= form_with model: project, class: "test-pickr" do |form| %>
          <%= form.text_field :deadline, class: "d-none",data: {input: ""} %>
          <a class="input-button" title="<%= project_deadline(project) %>" data-toggle>
            <i class="fa fa-calendar fa-white-shadow fa-dark-style" ></i>
          </a>
        <% end %>
      </div>
      <div class="col p-3 text-white font-weight-bold text-dark-shadow ">
        <span class="project-title"> <%= project.title %> </span>
      </div>
      <div class="p-3 fa-buttons col-auto">
        <%= link_to edit_project_path(project), data: { remote:true, toggle: 'modal' }, class:"px-2" do %>
          <i class="fa fa-pencil text-dark-shadow fa-heading-style"></i>
        <% end %>
        <span class="fa-heading-style">|</span>
        <%= link_to project, method: :delete, data: { remote: true, confirm: 'Are you sure?' }, class: "delete-project px-2" do %>
          <i class="fa fa-trash text-dark-shadow fa-heading-style"></i>
        <% end %>
      </div>
    </div>
  </li>

  <%= form_with model: [project, @task], class: 'new_task' do |task| %>
    <li class="d-flex list-group-item light p-0 light-grey new-task rounded-0" >
      <div class="m-1 pt-2 px-1">
        <a><i class="fa fa-plus fa-green-style" ></i></a>
      </div>
      <div class=" input-group ">
        <%= task.text_field :title,
        placeholder: "Start typing here to create a task..." , required: true,
        class:"form-control my-2 border-left-0 border-bottom-0 border-secondary"%>
          <div class="input-group-append">
              <%= task.submit "Add task", class:"btn my-2 mr-2 px-3 text-white font-weight-bold border-top border-secondary green-gradient text-dark-shadow" %>
          </div>
      </div>
    </li>
  <% end %>
  <div class="sortable">
    <% project.tasks.each do |task| %>
        <%= render partial: 'tasks/task', locals: { project: project, task: task} %>
    <% end %>
  </div>
</ul>

app/views/projects/create.js.erb
$("#modal-window").modal('hide');
$('div#projects').append("<%= j render 'project', project: @project %>");
configuredFlatpickr();

app/views/projects/destroy.js.erb
$('.delete-project').on('ajax:success', function() {
	$('ul#<%=dom_id(@project)%>').fadeOut().remove();
});

app/views/projects/edit.js.erb
$("#modal-window").modal('show').find(".modal-content").html("<%= j render 'form', project: @project %>");

app/views/projects/index.html.erb
<div id="projects">
  <%= render @projects %>
</div>

<div class="d-flex justify-content-center" id="new-project">
	<%= link_to new_project_path, data: { remote: true, toggle: 'modal' }, class:"btn m-4 p-2  font-weight-bold border-top 	border-secondary blue-gradient shadow"  do %>
		<i class="fa fa-plus px-1fa-white-shadow fa-dark-style"></i>
		<span class="mx-2 text-white text-dark-shadow" >Add TODO List</span>
	<%end%>
</div>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content border rounded">
    </div>
  </div>
</div>

app/views/projects/new.js.erb
$("#modal-window").modal('show').find(".modal-content").html("<%= j render 'form', project: @project %>");

app/views/projects/update.js.erb
$("#modal-window").modal('hide');
elem = $('ul#<%=dom_id(@project)%>');
elem.find('span.project-title').text("<%= @project.title %>");
elem.find("div.flatpickr a.input-button").first().attr("title", "<%= project_deadline(@project) %>");

app/views/tasks/_edit_task.html.erb
<%= form_with model: [project,task], method: :put do |form| %>
	<li class="d-flex list-group-item light p-0 light-grey new-task border-0" id="<%=dom_id(task)%>">
		<div class="m-1 pt-2 px-1">
			<a><i class="fa fa-pencil-square-o fa-green-style" ></i></a>
		</div>
		<div class=" input-group ">
			<%= form.text_field :title, required: true,
        class:"form-control my-2 border-left-0 border-bottom-0 border-secondary"%>
				<div class="input-group-append">
						<%= form.submit "Edit task", class:"btn my-2 mr-2 px-3 text-white font-weight-bold border-top border-secondary green-gradient text-dark-shadow" %>

				</div>
		</div>
	</li>
<% end %>

app/views/tasks/_task.html.erb
<li class="list-group-item p-0" id="<%=task.sortable_id%>">
  <div class="row mx-0 <%= "light-blue" if task.completed? %>" id="<%=dom_id(task)%>">

    <div class="col-auto border-right-red p-3 text-center">
	    <%= check_box_tag "", 1, task.completed?, data: { remote: true, url: toggle_project_task_path(project, task), method: :post } %>
	  </div>

		<div class="border-right col p-3 d-flex task-text <%= "text-decor-line" if task.completed? %>">
			<span class="truncate-text"><%=task.title%></span>
			<div class="col-auto fa-buttons flatpickr pl-2 pr-0 <%= "d-none" if task.completed? %>">
        <%= form_with model: [project, task], class: "test-pickr" do |form| %>
          <%= form.text_field :task_deadline, class: "d-none",data: {input: ""} %>
          <a class="input-button" title="<%= task_deadline(task) %>" data-toggle>
            <i class="fa fa-calendar " ></i>
          </a>
        <% end %>
      </div>
		</div>

    <div class="px-1 py-3 text-center col-auto fa-buttons">
      <a href="#" class="px-2">
        <i class="fa fa-unsorted text-secondary"></i>
      </a>

      <span>|</span>

      <%= link_to edit_project_task_path(project,task),data:{remote:true}, class:"px-2" do %>
        <i class="fa fa-pencil text-secondary"></i>
      <% end %>

      <span>|</span>

      <%= link_to project_task_path(project,task), method: :delete, data: { remote: true, confirm: 'Are you sure?'}, class: "delete-task px-2" do %>
        <i class="fa fa-trash text-secondary"></i>
      <% end %>
    </div>
  </div>
</li>

app/views/tasks/create.js.erb
$('ul#<%=dom_id(@project)%> div.sortable').append("<%= j render 'tasks/task', project: @project, task: @task %>");
$("ul#<%=dom_id(@project)%> .new_task")[0].reset();
squareEdges();
roundEdges();
railsSort();
configuredFlatpickr();

app/views/tasks/destroy.js.erb
$('#<%=dom_id(@task)%>').parent().fadeOut().remove();
roundEdges();

app/views/tasks/edit.js.erb
$('#<%=dom_id(@task)%>').parent().replaceWith("<%= j render 'tasks/edit_task', project: @project , task: @task %>");

app/views/tasks/new.js.erb
$("ul#<%=dom_id(@project)%> #task_title").attr("placeholder", "<%= j  @task.errors.full_messages[0] %>");

app/views/tasks/toggle.js.erb
<% if @task.completed? %>
  $('#<%=dom_id(@task)%>').addClass("light-blue")
    .find('div.task-text').addClass("text-decor-line")
    .find('div.flatpickr').addClass("d-none");
<% else %>
  $('#<%=dom_id(@task)%>').removeClass("light-blue")
    .find('div.task-text').removeClass("text-decor-line")
    .find('div.flatpickr').removeClass("d-none");
<% end %>

configuredFlatpickr();

app/views/tasks/update.js.erb
$('#<%=dom_id(@task)%>').parent().replaceWith("<%= j render 'tasks/task', project: @project , task: @task %>");
railsSort();
roundEdges();
configuredFlatpickr();